name: stactools-canelevation
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::gdal>=3.3
  - conda-forge::pdal
  - conda-forge::python-pdal
  - conda-forge::geos>=3.3
  - conda-forge::rasterio>=1.3
